FROM mcr.microsoft.com/devcontainers/base:ubuntu

ENV DENO_INSTALL=/home/vscode/.deno
RUN curl -fsSL https://deno.land/x/install/install.sh | sh

ENV PATH=${DENO_INSTALL}/bin:${PATH}

RUN deno install -A https://deno.land/x/deploy@1.9.0/deployctl.ts
ENV PATH=/root/.deno/bin:${PATH}

RUN deno cache src/main.ts